#!/usr/bin/env sh
set -eu

ROOT="${ROOT:-$(pwd)}"

echo "### Create student"
curl -i -s -X POST http://localhost:8081/students \
  -H "Content-Type: application/json" \
  --data-binary "@$ROOT/test/payloads/student-create.json"
echo

echo "### List students"
curl -i -s http://localhost:8081/students
echo

echo "### Get student"
curl -i -s http://localhost:8081/students/student-0
echo

echo "### Mark student as InTraining"
curl -i -s -X PATCH http://localhost:8081/students/student-0/status \
  -H "Content-Type: application/json" \
  --data-binary "@$ROOT/test/payloads/student-status-in-training.json"
echo
